import { Type, Typesystem, IOC } from "smallstack";

/**
 * THIS FILE IS AUTO-GENERATED AND WILL BE REPLACED ON ANY RE-GENERATION
 */

(() => {
    var typesystem: Typesystem = IOC.get<Typesystem>("typesystem");
    
    typesystem.addType(Type.fromDocument({"generatorOptions":{"destination":"local"},"collection":{"name":"pages"},"service":{"name":"PagesService","queries":[{"name":"getPageById","selector":{"_id":":id"}},{"name":"getAllPages","selector":{}},{"name":"getPageByName","selector":{"name":":name"}}]},"model":{"name":"Page","schema":[{"name":"name","type":"string"},{"name":"components","type":"object","optional":true,"blackbox":true},{"name":"socketConnections","type":"object[]","optional":true,"blackbox":true}]}}));

	typesystem.addType(Type.fromDocument({"generatorOptions":{"destination":"local"},"collection":{"name":"configuration"},"service":{"name":"ConfigurationService","queries":[{"name":"getConfiguration","selector":{"scope":"everywhere"}}]},"model":{"name":"Configuration","schema":[{"name":"key","type":"string","unique":true,"index":true},{"name":"value","type":"string"},{"name":"scope","type":"string","allowedValues":["server","everywhere"]}]}}));

	typesystem.addType(Type.fromDocument({"generatorOptions":{"destination":"local"},"model":{"name":"I18nText","schema":[{"name":"language","type":"string"},{"name":"value","type":"string"}]}}));

	typesystem.addType(Type.fromDocument({"generatorOptions":{"destination":"local"},"collection":{"name":"languages"},"service":{"name":"LanguageService","queries":[{"name":"getAllLanguages","selector":{}},{"name":"getLanguageByKey","selector":{"key":":key"}}]},"model":{"name":"Language","schema":[{"name":"key","type":"string"},{"name":"fallback","type":"string[]","optional":true}]}}));

	typesystem.addType(Type.fromDocument({"generatorOptions":{"destination":"local"},"collection":{"name":"localizations"},"service":{"name":"LocalizationService","queries":[{"name":"getLocalizationsForLanguage","selector":{"language":":languageKey"}},{"name":"getLocalizationForLanguage","selector":{"key":":key","language":":languageKey"}},{"name":"getLocalizations","selector":{},"sort":{"key":1}},{"name":"getLocalizedTextsByIds","selector":{"_id":{"$in":":ids:string[]"}}},{"name":"getLocalizedTextById","selector":{"_id":":id:string"}}]},"model":{"name":"LocalizedText","schema":[{"name":"key","type":"string"},{"name":"value","type":"string","optional":true},{"name":"language","type":"string"}]}}));

	typesystem.addType(Type.fromDocument({"generatorOptions":{"destination":"local"},"collection":{"name":"mediaformats"},"service":{"name":"MediaFormatService","queries":[{"name":"getMediaFormatByName","selector":{"name":":name"}},{"name":"getAllMediaFormats","selector":{}},{"name":"getMediaFormatsByIds","selector":{"_id":{"$in":":ids:string[]"}}},{"name":"getMediaFormatById","selector":{"_id":":id:string"}}]},"model":{"name":"MediaFormat","schema":[{"name":"name","type":"string","unique":true},{"name":"preprocessed","type":"boolean","defaultValue":true},{"name":"command","type":"string","optional":true,"allowedValues":["resize","scale","blur","cover"]},{"name":"parameters","type":"any","optional":true,"blackbox":true},{"name":"isDefault","type":"boolean","optional":true,"defaultValue":false}]}}));

	typesystem.addType(Type.fromDocument({"generatorOptions":{"destination":"local"},"collection":{"name":"medias"},"service":{"name":"MediaService","queries":[{"name":"getMediaByIds","selector":{"_id":{"$in":":ids:string[]"},"ownerId":"_currentLoggedInUser_"}},{"name":"getMediaById","selector":{"_id":":id:string"}},{"name":"getAllMedias"},{"name":"getMediasByTag","selector":{"tags":":tag"}}]},"model":{"name":"Media","schema":[{"name":"ownerId","type":"foreign","foreignType":"User","optional":true},{"name":"createdAt","type":"date"},{"name":"contentType","type":"string","optional":true},{"name":"availableFormatIds","type":"foreign[]","foreignType":"MediaFormat","optional":true,"defaultValue":[]},{"name":"tags","type":"string[]","optional":true,"defaultValue":[]}]}}));

	typesystem.addType(Type.fromDocument({"generatorOptions":{"destination":"local"},"collection":{"name":"uploadedfiles"},"service":{"name":"UploadedFileService","queries":[{"name":"getUploadedFilesByIds","selector":{"_id":{"$in":":ids:string[]"},"ownerId":"_currentLoggedInUser_"}},{"name":"getFileById","selector":{"_id":":id:string"},"ownerId":"_currentLoggedInUser_"}]},"model":{"name":"UploadedFile","schema":[{"name":"ownerId","type":"foreign","foreignType":"User","optional":true},{"name":"createdAt","type":"date"},{"name":"contentType","type":"string","optional":true}]}}));

	typesystem.addType(Type.fromDocument({"generatorOptions":{"destination":"local"},"collection":{"name":"navigation"},"service":{"name":"NavigationService","queries":[{"name":"getNavigationForType","selector":{"type":":type"}},{"name":"getNavigationEntryById","selector":{"_id":":id:string"}}]},"model":{"name":"NavigationEntry","schema":[{"name":"label","type":"string"},{"name":"icon","type":"string","optional":true},{"name":"route","type":"string"},{"name":"requiresAuthentication","type":"boolean","defaultValue":true},{"name":"loginStateName","type":"string","optional":true},{"name":"requiredRole","type":"string","optional":true},{"name":"templateUrl","type":"string","optional":true},{"name":"controllerName","type":"string","optional":true},{"name":"pageId","type":"foreign","foreignType":"Page","optional":true},{"name":"visible","type":"boolean","optional":true,"defaultValue":true},{"name":"index","type":"number"},{"name":"type","type":"string","optional":true},{"name":"stateName","type":"string"},{"name":"abstract","type":"boolean","optional":true,"defaultValue":false},{"name":"defaultRoute","type":"boolean","optional":true,"defaultValue":false},{"name":"substateOfId","type":"foreign","foreignType":"NavigationEntry","optional":true},{"name":"badge","type":"number","optional":true},{"name":"trackingEnabled","type":"boolean","defaultValue":true}]}}));

	typesystem.addType(Type.fromDocument({"generatorOptions":{"destination":"local"},"collection":{"name":"pushnotifications"},"service":{"name":"PushNotificationService","queries":[{"name":"getAllPushNotifications","selector":{},"sort":{"createdAt":1},"access":{"hasRole":{"role":"backoffice.pushnotifications"}}}]},"model":{"name":"PushNotification","schema":[{"name":"subjects","type":"object","blackbox":true},{"name":"contents","type":"object","blackbox":true},{"name":"createdAt","type":"date"},{"name":"sentAt","type":"date","optional":true},{"name":"reachedCount","type":"number","defaultValue":0},{"name":"sent","type":"boolean","defaultValue":false}]}}));

	typesystem.addType(Type.fromDocument({"collection":{"name":"emails"},"service":{"name":"EmailService","queries":[{"name":"getAllMails","selector":{},"sort":{"createdAt":-1},"access":{"hasRole":{"role":"backoffice.emails"}}}]},"model":{"name":"SmallstackEmail","schema":[{"name":"createdAt","type":"date"},{"name":"sentAt","type":"date","optional":true},{"name":"from","type":"string"},{"name":"to","type":"string[]","optional":true},{"name":"toUserIds","type":"foreign[]","foreignType":"User","optional":true},{"name":"cc","type":"string[]","optional":true},{"name":"bcc","type":"string[]","optional":true},{"name":"subjects","type":"object","blackbox":true},{"name":"contents","type":"object","blackbox":true},{"name":"htmlMail","type":"boolean","optional":true,"defaultValue":false},{"name":"status","type":"string","defaultValue":"CREATED","allowedValues":["CREATED","SCHEDULED","SENDING","SENT"]}]}}));

	typesystem.addType(Type.fromDocument({"collection":{"name":"emailtemplates"},"service":{"name":"EmailTemplatesService","queries":[{"name":"getAllTemplates","selector":{},"access":{"hasRole":{"role":"backoffice.emails"}}}]},"model":{"name":"EmailTemplate","schema":[{"name":"name","type":"string"},{"name":"from","type":"string"},{"name":"subjects","type":"object","blackbox":true},{"name":"contents","type":"object","blackbox":true},{"name":"htmlMail","type":"boolean","optional":true,"defaultValue":false},{"name":"systemTemplate","type":"boolean","optional":true,"defaultValue":false}]}}));

	typesystem.addType(Type.fromDocument({"collection":{"name":"messages"},"service":{"queries":[{"name":"getMyMessages","selector":{"participantIds":"_currentLoggedInUser_"},"sort":{"date":-1}},{"name":"getMyMessagesWithUser","selector":{"participantIds":[":userId:string","_currentLoggedInUser_"]},"sort":{"date":-1}}]},"model":{"name":"Message","schema":[{"name":"ownerId","type":"foreign","foreignType":"User","optional":true},{"name":"date","type":"date"},{"name":"text","type":"string","min":1},{"name":"participantIds","type":"foreign[]","foreignType":"User","min":2},{"name":"readIds","type":"foreign[]","foreignType":"User","optional":true},{"name":"context","type":"string","optional":true}]}}));

	typesystem.addType(Type.fromDocument({"collection":{"name":"news"},"service":{"name":"NewsService","queries":[{"name":"getAllNews","selector":{}},{"name":"getAllUnreadNews","selector":{"seenByIds":{"$nin":["_currentLoggedInUser_"]}}}]},"model":{"name":"News","schema":[{"name":"labelIds","type":"foreign[]","foreignType":"LocalizedText","defaultValue":[]},{"name":"date","type":"date"},{"name":"seenByIds","type":"foreign[]","foreignType":"User","optional":true,"defaultValue":[]},{"name":"contentIds","type":"foreign[]","foreignType":"LocalizedText","defaultValue":[]}]}}));

	typesystem.addType(Type.fromDocument({"generatorOptions":{"destination":"local"},"collection":{"name":"roles"},"service":{"name":"RolesService","queries":[{"name":"getRoleByName","selector":{"name":":name:string"}},{"name":"getRoleById","selector":{"_id":":id:string"}},{"name":"getRolesByIds","selector":{"_id":{"$in":":ids:string[]"}}},{"name":"getAllRoles"}],"securedmethods":[]},"model":{"name":"Role","schema":[{"name":"name","type":"string","unique":true,"index":true,"min":3},{"name":"subRoleIds","type":"foreign[]","foreignType":"Role","optional":true,"defaultValue":[]}]}}));

	typesystem.addType(Type.fromDocument({"generatorOptions":{"destination":"local"},"collection":{"name":"users"},"service":{"name":"UserService","queries":[{"name":"getUsersByIds","selector":{"_id":{"$in":":ids"}},"fields":{"profile.displayName":1,"profile.avatarUrl":1,"profile.avatarId":1,"services.facebook.id":1,"services.google.picture":1,"roleIds":1}},{"name":"getUserById","selector":{"_id":":id"},"fields":{"profile.displayName":1,"profile.avatarUrl":1,"profile.avatarId":1,"services.facebook.id":1,"user.services.google.picture":1,"roleIds":1}},{"name":"getAllUsers","selector":{},"fields":{"profile.displayName":1,"profile.avatarUrl":1,"profile.avatarId":1,"services.facebook.id":1,"user.services.google.picture":1,"roleIds":1}},{"name":"getMyUser","selector":{"_id":"_currentLoggedInUser_"},"fields":{"services.password":0,"services.resume":0,"services.facebook.expiresAt":0,"services.facebook.accessToken":0,"services.google.accessToken":0,"services.google.idToken":0,"services.google.expiresAt":0,"services.google.scope":0,"services.google.verified_email":0,"services.email.verificationTokens":0}}],"skipSecuredMethodsGeneration":true,"securedmethods":[{"name":"updateProfileDetails","parameters":["newValues:any"],"returns":"any"}]},"customTransformMethod":"transformUsers","model":{"name":"User","schema":[{"name":"profile","type":"Object"},{"name":"emails","type":"Object[]","optional":true},{"name":"createdAt","type":"number"},{"name":"services","type":"Object","optional":true},{"name":"roleIds","type":"foreign[]","optional":true,"foreignType":"Role","defaultValue":[]}],"implements":"Meteor.User"}}));

	

})();
