/**
 * THIS FILE IS AUTOGENERATED
 */
export * from "./services/BetgroupsService";
export * from "./services/BetsService";
export * from "./services/CompetitionMatchesService";
export * from "./services/CompetitionRoundsService";
export * from "./services/CompetitionTeamsService";
export * from "./services/CompetitionsService";
export * from "./services/DevicesService";


export * from "./models/BetGroup";
export * from "./models/Bet";
export * from "./models/CompetitionMatch";
export * from "./models/CompetitionRound";
export * from "./models/CompetitionTeam";
export * from "./models/Competition";
export * from "./models/Device";


export * from "./collections/BetgroupsCollection";
export * from "./collections/BetsCollection";
export * from "./collections/CompetitionMatchesCollection";
export * from "./collections/CompetitionRoundsCollection";
export * from "./collections/CompetitionTeamsCollection";
export * from "./collections/CompetitionsCollection";
export * from "./collections/DevicesCollection";



export * from "./init";
export * from "./typesystem";
export * from "./index_custom";
