/**
 * THIS FILE IS AUTOGENERATED
 */
export * from "./services/EmailService";
export * from "./services/EmailTemplatesService";
export * from "./services/MessagesService";
export * from "./services/NewsService";


export * from "./models/SmallstackEmail";
export * from "./models/EmailTemplate";
export * from "./models/Message";
export * from "./models/News";


export * from "./collections/EmailsCollection";
export * from "./collections/EmailtemplatesCollection";
export * from "./collections/MessagesCollection";
export * from "./collections/NewsCollection";

