/// <reference path="../typedefinitions/generated.d.ts" />

// THIS FILE IS AUTO-GENERATED BY 'smallstack compile'! PLEASE IGNORE THE FILE IN YOUR SCM!

declare var versions: { smallstack: string, project: string, compileDate: number, projectName: string };

versions = {
	smallstack: "0.7.0",
	project: "0.3.0-SNAPSHOT",
	compileDate: 1482217996198,
	projectName: "cuppy"
}

if (Meteor.isClient) {
	console.log('smallstack: ' + versions.smallstack);
	console.log(versions.projectName + ': ' + versions.project);
	console.log('compile time: ' + moment(versions.compileDate).format());
	console.log(' ');
}