/**
 * This file is auto-generated by "smallstack syncproject", but not executed/imported automatically!
 * You don't have to use this file at all, but it shows what to do to bootstrap smallstack in a meteor
 * environment on the server side.
 *
 * How-to use this file:
 *
 * import "./imports/initServer";
 * (...)
 *
 * initServer();
 */


import { Logger } from "@smallstack/core-common";
import { initCoreCommon } from "@smallstack/core-common";
import { initCoreServer } from "@smallstack/core-server";
import { createDatalayerCollections, initializeTypesystem, registerDatalayerServices } from "@smallstack/datalayer";
import { initMeteorCommon } from "@smallstack/meteor-common";
import { createDefaultAdministrator, initMeteorServer, kadiraSetup } from "@smallstack/meteor-server";

export function initServer() {

    initializeTypesystem();
    initCoreCommon();
    initMeteorCommon();
    initCoreServer();
    initMeteorServer();

    createDatalayerCollections();
    registerDatalayerServices();
    createDefaultAdministrator();
    // kadiraSetup();

}
