/**
 * This file is auto-generated by "smallstack syncproject", but not executed/imported automatically!
 * You don't have to use this file at all, but it shows what to do to bootstrap smallstack in a meteor
 * environment on the server side. 
 * 
 * How-to use this file: 
 * 
 * import "./imports/initServer";
 * (...)
 * 
 * initServer();
 */


import { initCoreServer } from "@smallstack/core-server";
import { Logger } from "@smallstack/core-common";
import { initCoreCommon } from "@smallstack/core-common";
import { initMeteorServer, createDefaultAdministrator } from "@smallstack/meteor-server";
import { MeteorBaseCollection, initMeteorCommon } from "@smallstack/meteor-common";
import { createDatalayerCollections, registerDatalayerServices, initializeTypesystem } from "@smallstack/datalayer";

export function initServer() {
    
    initializeTypesystem();
    initCoreCommon();
    initMeteorCommon();
    initCoreServer();
    initMeteorServer();

    createDatalayerCollections();
    registerDatalayerServices();
    createDefaultAdministrator();

}